// <auto-generated />
using ChatBotGO.WebApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ChatBotGO.WebApp.Migrations
{
    [DbContext(typeof(Contexto))]
    [Migration("20220401033130_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ChatBotGO.WebApp.Models.RespostaChat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Mensagem")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Mensagem");

                    b.Property<string>("Resposta")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Resposta");

                    b.HasKey("Id");

                    b.ToTable("RespostaChat");
                });
#pragma warning restore 612, 618
        }
    }
}
